### ISSUE TITLE
UserStory: Visualisation des résultats (Visiteur)

### ISSUE THREAD

**Issue by Soulou** [ensiie/UnsapaIPW#19]
Je suis un visiteur
Je clique sur l'icone "Tous les examens"
Je vois la liste des examens terminés avec la moyenne des notes attribuées

**Comment by Lascar-Usuel** [comment]
Afin de s'en tenir au sujet, je vais ajouter une page "Stats" accessible à tous (visiteurs, étudiants et respos TD).
Dans un premier temps on va juste afficher la liste des promos avec leur moyenne générale (comme demandé dans le sujet).

**Comment by Lascar-Usuel** [comment]
En cours de réalisation:  #64
