### ISSUE TITLE
UserStory: Créer un examen (Professeur)

### ISSUE THREAD

**Issue by guparan** [ensiie/UnsapaIPW#21]
Je suis un professeur
Je vais dans la rubrique Examens (/exams)
Je clique sur le bouton "Créer un examen"
Je remplis le formulaire de création d'examen
    -> titre
    -> promotion (avec détails pour désélectionner des étudiants si besoin)
    -> échéance
    -> coefficient
    -> description
Je clique sur le bouton "Créer l'examen"
Je me retrouve dans la rubrique des Examens
L'examen créé se retrouve en haut de la liste

**Comment by Soulou** [comment]
Done : #32 #29 #15
Plus des petits détails qui se cachent dans d'autres commits.
