### ISSUE TITLE
UserStory: Ajouter une promotion (Administrateur)

### ISSUE THREAD

**Issue by Soulou** [ensiie/UnsapaIPW#22]
Je suis un administrateur.
Je me rend sur le panneau d'administration (/admin)
Je vois la liste des promotions
Je clique sur '+' pour en ajouter une

**Comment by guparan** [comment]
Je relève le défi :D

**Comment by Soulou** [comment]
Wouhouhouhou !

Crée un pull request dès le début comme ça à chaque fois que tu push ta 
branches, on peut voir les modifs =D
