### ISSUE TITLE
UserStory: Editer les participants à un examen (Professeur)

### ISSUE THREAD

**Issue by guparan** [ensiie/UnsapaIPW#23]
Je suis un professeur
Je suis dans la catégorie Examens
Je clique sur le bouton "modifier" sur la ligne de l'Examen
J'accède au formulaire de création d'Examen rempli avec les infos de cet Exam
Je clique sur le bouton "+" à coté du choix de la promo
J'affine les participants en cochant/décochant
Je clique sur le bouton "Enregistrer les modifications"
Je suis redirigé vers la catégorie Examens

**Comment by Soulou** [comment]
It's done #61
