### ISSUE TITLE
UserStory: S'inscrire (Visiteur)

### ISSUE THREAD

**Issue by guparan** [ensiie/UnsapaIPW#24]
Je suis un visiteur
Je suis par défaut sur la page des News (/news)
Je clique sur le bouton "S'inscrire"
Je renseigne les champs du formulaire d'inscription
    -> Login
    -> Email
    -> Nom
    -> Prénom
    -> Promo
    -> Adresse (fac)
    -> Code Postal (fac)
    -> Ville (fac)
-> Téléphone (fac)
Je clique sur le bouton "Valider"
Je suis redirigé vers la catégorie Examens

**Comment by Lascar-Usuel** [comment]
Ajouter les champs suivant au formulaire existant :
-> Promo
-> Téléphone
-> éventuellement les champs relatifs à l'adresse postale

Rectifier le nom des champs "Nom" et "Prénom"

![Problème nom et prénom](http://i.imgur.com/Jh5k7.png)

**Comment by Soulou** [comment]
C'est fait !
#63

![Image](http://soulou.fr/~leo/d.png)
