### ISSUE TITLE
Template graphique

### ISSUE THREAD

**Issue by Soulou** [ensiie/UnsapaIPW#5]
À quoi doit ressembler notre site ?

Je vous propose cette outil pour faire des mockups :

http://builds.balsamiq.com/

exemple :

![Exemple Mockup](http://soulou.fr/~leo/ipwmockup.png)

**Comment by guparan** [comment]
Balsamiq c'est bien, mais payant :(

**Comment by Soulou** [comment]
Nan t'as juste un popup toutes les 5 minutes il me semble.

## 

Léo Unbekandt
1A ENSIIE Strasbourg
École Nationale Supérieure d'Informatique
pour l'Industriel et l'Entreprise
Le 24 avr. 2012 15:10, "guparan" <
reply@reply.github.com>
a écrit :

**Comment by guparan** [comment]
Ah, l'année derrnière quand je m'en suis servi on n'avait droit qu'à une version d'essai gratuite. Si c'est des popup c'est mieux :)
