### ISSUE TITLE
Enlever l'élément state d'exam

### ISSUE THREAD

**Issue by Soulou** [ensiie/UnsapaIPW#56]
Oui on en a pas besoin, on peut considérer que si la date actuelle > date de l'exam, c'est fini, sinon c'est en court. C'est en fait ridicule d'avoir un état.

Vous en pensez quoi ?

**Comment by Lascar-Usuel** [comment]
Je suis d'accord, il suffit de regarder la date actuelle et ce comparer comme tu l'as dit.

**Comment by Soulou** [comment]
Done #87
