### ISSUE TITLE
Ajout d'un examen: détails -> liste étudiants vide

### ISSUE THREAD

**Issue by Lascar-Usuel** [ensiie/UnsapaIPW#90]
![no students](http://i.imgur.com/fXzHF.png)

**Comment by Soulou** [comment]
Oui j'ai vu,  je m'en occupe demain.

## 

Léo Unbekandt
1A ENSIIE Strasbourg
École Nationale Supérieure d'Informatique
pour l'Industriel et l'Entreprise
Le 17 mai 2012 23:19, "Lucas SAUREL" <
reply@reply.github.com>
a écrit :

**Comment by Lascar-Usuel** [comment]
On dirait bien que c'est réglé. On ferme ?

**Comment by Soulou** [comment]
Oui !

## 

Léo Unbekandt
Engineer student @ ENSIIE Strasbourg FR
Soulou on Freenode/Twitter
+33 6 72 65 20 42
